GET http://localhost:3000/api/categories/63f61a47283e3bd8d78420d3
###
GET http://localhost:3000/api/categories
###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "title": "Healthy food",
    "image": "#",
    "description": "#"
}
###
PUT http://localhost:3000/api/categories/63f61a47283e3bd8d78420d3
Content-Type: application/json

{
    "title": "Mixes",
    "image": "gwehewhwe",
    "description": "gewhwe"
}
