GET http://localhost:3000/api/products/63f5e60862ecb4f788b270eb
###
GET http://localhost:3000/api/products
###
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "title": "Green",
    "image": "hwerwqtwq",
    "volume": 500,
    "ingredients": {
        "ingr1": "Celery",
        "ingr2": "Apple",
        "ingr3": "Spinach",
        "ingr4": "Spirulina",
        "ingr5": "Ice"
    },
    "nutritionalValue": {
        "protein": 8,
        "carbohydrates": 40,
        "fat": 5
    },
    "shelfLife": 80,
    "storageConditions": "In the fridge",
    "price": 299,
    "category": "63f5e1ea5fbd8a9e48d08851"
}