GET http://localhost:3000/api/products/63f6370469e986c09f2d4146
###
GET http://localhost:3000/api/products
###
GET http://localhost:3000/api/products/category/63f6363b69e986c09f2d412f
###
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "title": "Pomegranate juce",
    "image": "#",
    "volume": 500,
    "ingredients": {
        "ingr1": "Pomegranate",
        "ingr2": "Ice"
    },
    "nutritionalValue": {
        "protein": 10,
        "carbohydrates": 30,
        "fat": 8
    },
    "shelfLife": 60,
    "storageConditions": "In the fridge",
    "price": 359,
    "category": "63f6363b69e986c09f2d412f"
}
###
PUT http://localhost:3000/api/products/63f6376169e986c09f2d4148
Content-Type: application/json

{
    "title": "Pomegranate juice",
    "image": "https://raw.githubusercontent.com/RickardTimergalejevs/VitaJuiceShop/4301e8d4386e7988c897d897549be48d88596f72/Client/img/logo.png",
    "volume": 500,
    "ingredients": {
        "ingr1": "Pomegranate",
        "ingr2": "Ice"
    },
    "nutritionalValue": {
        "protein": 10,
        "carbohydrates": 30,
        "fat": 8
    },
    "shelfLife": 60,
    "storageConditions": "In the fridge",
    "price": 400,
    "category": "63f6363b69e986c09f2d412f"
}